### ISSUE TITLE
curl: (77) Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by ugowego** [alexryabtsev/docker-workshop#1]
I've got error when I run test-curl containers.

`curl: (77) Problem with the SSL CA cert (path? access rights?)`

I've solved this problem adding the following to Dockerfile

`RUN apt-get install --no-install-recommends --no-install-suggests -y ca-certificates`

Hope to be helpful.

**Comment by captify-alazorenko** [comment]
Thanks, @ugowego, it was helpful!
Personally, I would add the following. To get the facebook example working, you need to follow these steps:

1. Change the following line of Dockerfile:
`RUN apt-get install --no-install-recommends --no-install-suggests -y curl` to
`RUN apt-get install --no-install-recommends --no-install-suggests -y curl ca-certificates`
2. Delete the current docker image as follows:
`docker rmi $(docker images test-curl -q)`
3. Build the image from Dockerfile again:
`docker build . -t test-curl`

After these steps, example should work.

**Comment by ugowego** [comment]
It works. Thanks.
